services:
  gameplaydb:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Your_password123
    image: microsoft/mssql-server-linux
    ports:
      - "1433"
  gameplaynglr:
    build:
      context: ./quizrt
      dockerfile: Dockerfile
    ports:
      - "4202:4200"
    volumes:
      - ".:/quizrt/usr/src/gameplayapp"
      - /quizrt/usr/src/gameplayapp/node_modules
  gameplayweb:
    build: ./asp-back
    environment:
      SQLSERVER_HOST: Server=gameplaydb;Database=Quiztest3DBLinux;User=sa;Password=Your_password123
    links:
      - gameplaydb
    ports:
      - "8082:5000"
version: "3"